alias v='nvim'
alias vv='nvim .'
alias visshk='nvim ~/.ssh/known_hosts'
alias visshc='nvim ~/.ssh/config'
alias vibash='nvim ~/.bashrc'
alias viz='nvim ~/.config/zsh/'
alias vio='nvim ~/.config/oh-my-zsh/custom/'
alias vc='NVIM_APPNAME=nvimc nvim'
