#!/bin/bash

current_dir=$(pwd)
config_dir="$HOME/.config/"

backup_directory="/home/colombos/auto_config"

config_targets=(
	"nvim"
	"kitty"
	"i3"
	"polybar"
	"rofi"
	"dunst"
	"lazygit"
	"autorandr"
	"scripts"
	"zsh"
	"oh-my-zsh/custom/"
	"dunst"
	"tmux"
	"tmuxinator"
	"sesh"
)
for target in "${config_targets[@]}"; do
	mkdir -p "$backup_directory/config/$target"
	cp -rf "$config_dir/$target" "$backup_directory/config/$target"
done

if [[ -n $2 ]]; then
	message=$1
else
	message="Automatic Commit"
fi

cd "$backup_directory" || exit

output=$({ git add . && git commit -m "$message" && git push; } 2>&1)

notify-send "$output"
echo "$output"

cd "$current_dir" || exit
