#!/bin/bash

VERSION="$1"

if [ -z "$VERSION" ]; then
	VERSION=$(python --version | awk '{print $2}' | grep -oP '^[0-9].[0-9]{2}')
fi

if ! command -v "python$VERSION" >/dev/null; then
	echo "Python $VERSION is not installed."
	exit 1
fi

python$VERSION -m venv venv
echo "export PYTHONPATH=$(pwd)" >>venv/bin/envs.sh
