# Configuration
home: ~/.config/nap/naps/
default_language: bash
theme: nord

# Colors
background: "#c0caf5"
foreground: "#394b70"
primary_color: "#394b70"
primary_color_subdued: "#1d202f"
green: "#9ece6a"
bright_green: "#96E245"
bright_red: "#ff007c"
red: "#f7768e"
black: "#1d202f"
gray: "#c0caf5"
white: "#DADFF7"
